### ISSUE TITLE
"No reader function for tag object" error on certain JVM versions

### ISSUE THREAD

**Issue by pmonks** [noisesmith/lein-git-info-edn#3]
# Steps to reproduce:
1. in a locally cloned git repository, run `lein git-info-edn` to generate a `deploy-info.edn` file in the `resources` subdirectory
2. run `lein repl`
3. type in the following code:

```clojure
(require '[clojure.edn :as edn])
(require '[clojure.java.io :as io])
(edn/read-string (slurp (io/resource "deploy-info.edn")))
```

## Expected result:
* `deploy-info.edn` file is loaded and parsed, returning a map

## Actual result:
* The following error message is displayed:
```text
Execution error at user/eval2175 (REPL:1).
No reader function for tag object
```

## Environmental information
Note that this behaviour is JDK version specific.  On v1.8.0_191 (LTS) this code functions as expected, however on v1.8.0_242 (LTS), v11.0.2 (LTS), and v14+36-1461 (FR) it fails as described above.

## Problematic data
Manually removing the `:date #object[java.util.Date ...` element from the generated `deploy-info.edn` file allows the above code to work on all tested JVM versions.

# A possible solution
Update the plugin to emit a [built-in `#inst` tagged literal](https://github.com/edn-format/edn#built-in-tagged-elements) for the `:date` element, instead of relying on a custom `#object` tagged literal.

**Comment by noisesmith** [comment]
I'm surprised that the Date object isn't outputtting as an inst - what clojure version are you using?

```
(ins)user=> *clojure-version*
{:major 1, :minor 10, :incremental 1, :qualifier nil}
(cmd)user=> (pr-str (java.util.Date.))
"#inst \"2020-04-17T20:46:57.626-00:00\""
```

**Comment by pmonks** [comment]
@noisesmith looks like the latest version of leiningen (v2.9.3) uses Clojure 1.10.0, despite what a project's own `project.clj` might require.  For example running `lein repl` in a non-project folder I can reproduce this at will:

```
$ lein repl
nREPL server started on port 54644 on host 127.0.0.1 - nrepl://127.0.0.1:54644
REPL-y 0.4.4, nREPL 0.6.0
Clojure 1.10.0
OpenJDK 64-Bit Server VM 11.0.2+9
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> (pr-str (java.util.Date.))
"#object[java.util.Date 0x4dae442c \"Fri Apr 17 14:09:50 PDT 2020\"]"
```

FWIW I can't find a fix for this regression mentioned specifically in the [1.10.1 change log](https://github.com/clojure/clojure/blob/master/changes.md#changes-to-clojure-in-version-1101), not that that document is necessarily exhaustive.

**Comment by pmonks** [comment]
If my recollection is correct (and keeping in mind it's been 4 or 5 years since I dabbled with plugins), leiningen plugins always run in leiningen's "core" JVM process (which presumably picks up whatever Clojure version leiningen was last built against), not the "subsidiary" JVM process it starts for the project's own code (and which presumably picks up the Clojure version from the `project.clj`).  Meaning, a project author can't fix this issue simply by specifying Clojure v1.10.1 in their `project.clj`, since lein-git-info-edn runs on leiningen's own JVM and Clojure version, not that of the project itself.

I've linked the relevant leiningen issue ([#2675](https://github.com/technomancy/leiningen/issues/2675)).

**Comment by pmonks** [comment]
(also, apologies for all of the edits on these comments - it's been a very long time since I last did anything leiningen plugin related, so I'm having to double check that I'm using all the correct terminology...  😉)

**Comment by pmonks** [comment]
I just realised that my test above (running `(pr-str (java.util.Date.))` in a REPL) doesn't prove anything about the Clojure version used in the "core" leiningen JVM, since all code typed at the REPL is executed in the "subsidiary" REPL JVM.

So I added `(println *clojure-version*)` to the top of the plugin code, ran the plugin, and the output was `{:major 1, :minor 10, :incremental 0, :qualifier nil}` (i.e. leiningen is indeed using v1.10.0 in its "core" JVM, despite what the [release notes](https://github.com/technomancy/leiningen/releases/tag/2.9.2) say).

**Comment by pmonks** [comment]
[The comments on this commit seem to confirm that something strange is going on in leiningen](https://github.com/technomancy/leiningen/commit/d4aec407c677a9672e2b0150c31e913bc05c429a#commitcomment-37921092).

**Comment by pmonks** [comment]
See also PR #5.

**Comment by pmonks** [comment]
Just of interest, with PR #5 merged to `master` will you be pushing out a v0.2.2 in the near future?

**Comment by noisesmith** [comment]
yes - apologies for the delay, I don't use this at work like I once did so it tends to be on the back burner, but I will be doing another release

**Comment by pmonks** [comment]
No worries, and no hurry - just wanted to confirm that a release would be coming along.

**Comment by noisesmith** [comment]
looks like it is now available
```
% lein git-info-edn
Retrieving org/noisesmith/git-info-edn/0.2.2/git-info-edn-0.2.2.pom from clojars
Retrieving org/noisesmith/git-info-edn/0.2.2/git-info-edn-0.2.2.jar from clojars
justin.smith@C02ZW014LVDN lein-git-info-edn % cat resources/deploy-info.edn
{:hash "84696dc71aa9e781eeb37fb36551426041b9d103",
 :status
 "On branch master\nYour branch is up to date with 'origin/master'.\n\nUntracked files:\n  (use \"git add <file>...\" to include in what will be committed)\n\n\tresources/\n\nnothing added to commit but untracked files present (use \"git add\" to track)",
 :date #inst "2020-04-23T19:45:49.149374Z"}
```
(couldn't resist being a bit meta)
